### ISSUE TITLE
Incorrect block and "isClassInSession" value returned

### ISSUE THREAD

**Issue by Veldrovive** [ClassyCreations/ScheduleCheck#1]
The Api currently always returns true for isClassInSession and C block for the current block. I know that you already know about this, but it would be nice to have it fixed.
Also, no I can't do that because I have no idea how ScheduleCheck even works.

**Comment by HeroCC** [comment]
Yep, I figured out why. I made a hasty commit and a test failed, resulting in a botched heroku deploy where stuff got frozen. It should be fixed in 21a4cb7523e3a3a533fd14570dbbceadb8a92eb0 now, let me know if not
