### ISSUE TITLE
Improve backend Cache system

### ISSUE THREAD

**Issue by Veldrovive** [ClassyCreations/ScheduleCheck#2]
* Refresh more often when blocks are expected to change
  * In the prior and post 5 minutes during expected block change
* Do not stall web requests during refreshing
  * Right now it stalls all web requests and runs the jar multiple times, this is not good
* Be comparable with future web hooks
  * Webhooks will be in a future ticket, but ensure the refresh / cache system still works when we eventually migrate to that
* Ensure it is tolerant of user-specific requests
  * Right now it accepts a username and password post parameter, ensure the user specific stuff is still not cached

**Comment by HeroCC** [comment]
The second and fourth bullets will be fixed in #3, and the other two will likely be much easier to complete with Spring in the future
